name = "night"
entrypoint = "main.night"
extensions = [
  "night"
]
packages = [
  "wget",
  "unzip"
]
setup = [
  "cd /tmp",
  "wget -q https://repl.it/@DynamicSquid/Night.zip",
  "unzip -q -o Night.zip \"./night\"",
  "cp -f night /usr/bin/night"
]

[run]
command = [
  "night",
  "main.night"
]

[tests]
  
  [tests.hello]
  code = "print \"hello\\n\";"
  output = "hello\n"
