name = "stekovaya"
entrypoint = "main.stk"
extensions = [
  "stk"
]
packages = [
  "mono-complete",
  "unzip",
  "wget"
]
setup = [
  "cd /usr/src",
  "wget -q https://repl.it/@theforarkld/Stekovaya.zip",
  "unzip -q -o -d stekovaya Stekovaya.zip \"stkvy.exe\"",
  "rm -f Stekovaya.zip"
]

[run]
command = [
  "/bin/bash",
  "-c",
  "mono /usr/src/stekovaya/stkvy.exe main.stk"
]

[tests]

  [tests.hello]
  code = "STR hello END MSG"
  output = "hello\n"
