name = "stekovaya"
entrypoint = "main.stk"
extensions = [
  "stk"
]
packages = [
  "mono-complete",
  "unzip",
  "wget"
]
setup = [
  "mkdir -p ~/bin/stekovaya",
  "cd ~/bin/stekovaya",
  "wget -q https://repl.it/@theforarkld/Stekovaya.zip",
  "unzip -q -o Stekovaya.zip \"stkvy.exe\"",
  "rm Stekovaya.zip",
  "echo ~/bin/stekovaya"
]

[run]
command = [
  "mono",
  "~/bin/stekovaya/stkvy.exe main.stk"
]

[tests]

  [tests.hello]
  code = "STR hello END MSG"
  output = "hello\n"
