name = "stekovaya"
entrypoint = "main.stk"
extensions = [
  "stk"
]
packages = [
  "mono-complete"
]
setup = [
  "cd /tmp",
  "wget -q https://repl.it/@theforarkld/Stekovaya.zip",
  "unzip -q -o -d stekovaya Stekovaya.zip \"stkvy.exe\"",
  "rm -f Stekovaya.zip",
  "mv stkvy.exe /usr/bin/stkvy.exe"
]

[run]
command = [
  "mono",
  "/usr/bin/stkvy.exe",
  "main.stk"
]

[tests]

  [tests.hello]
  code = "STR hello END MSG"
  output = "hello\n"
