name = "stekovaya"
entrypoint = "main.stk"
extensions = [
  "stk"
]
packages = [
  "mono-complete",
  "unzip",
  "wget"
]
setup = [
  "mkdir -p $HOME/bin",
  "cd $HOME/bin",
  "wget -q https://repl.it/@theforarkld/Stekovaya.zip",
  "unzip -q -o Stekovaya.zip \"stkvy.exe\"",
  "rm Stekovaya.zip"
]

[run]
command = [
  "mono",
  "$HOME/bin/stkvy.exe",
  "main.stk"
]

[tests]

  [tests.hello]
  code = "STR hello END MSG"
  output = "hello\n"
